# Generated by Django 4.1.5 on 2023-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_topic_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='topic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
