# Generated by Django 4.1.5 on 2023-02-28 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0003_alter_commentmodel_topic_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.ManyToManyField(related_name='Trip_Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
