# Generated by Django 4.1.5 on 2023-03-04 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0005_remove_commentmodel_likes_remove_commentmodel_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='LIKES',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
