# Generated by Django 4.1.5 on 2023-03-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_commentmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='LIKES',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.event'),
        ),
    ]
