# Generated by Django 4.1.5 on 2023-03-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_remove_commentmodel_likes_commentmodel_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='topic',
            new_name='location',
        ),
    ]
