# Generated by Django 4.1.5 on 2023-03-08 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0008_rename_topic_commentmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='liked',
            field=models.ManyToManyField(related_name='BlogPost_Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
