# Generated by Django 4.1.5 on 2023-03-08 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0009_commentmodel_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='liked',
        ),
        migrations.AddField(
            model_name='event',
            name='liked',
            field=models.ManyToManyField(related_name='BlogPost_Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
