# Generated by Django 4.1.5 on 2023-03-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_remove_event_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='location',
            new_name='event',
        ),
    ]
