# Generated by Django 4.1.5 on 2023-03-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='image_comment',
        ),
    ]
