# Generated by Django 4.1.5 on 2023-03-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_rename_title_image_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_comment',
            new_name='Comment',
        ),
    ]
