# Generated by Django 4.1.5 on 2023-03-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_rename_image_comment_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
