# Generated by Django 4.1.5 on 2023-03-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='like',
        ),
    ]
