# Generated by Django 4.1.5 on 2023-03-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0018_remove_commentmodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='host',
        ),
    ]
