# Generated by Django 4.1.5 on 2023-03-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
