# Generated by Django 4.1.5 on 2023-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0021_delete_image_commentmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
