# Generated by Django 4.1.5 on 2023-03-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0022_alter_commentmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='event',
        ),
    ]
