# Generated by Django 4.1.5 on 2023-03-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0023_remove_commentmodel_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.event'),
        ),
    ]
