# Generated by Django 4.1.5 on 2023-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0024_commentmodel_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
