# Generated by Django 4.1.5 on 2023-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_commentmodel_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
