# Generated by Django 4.1.5 on 2023-03-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_alter_commentmodel_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='videofile',
            new_name='video',
        ),
    ]
