# Generated by Django 4.1.5 on 2023-03-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0029_likemodel_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
