# Generated by Django 4.1.5 on 2023-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0030_likemodel_unlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
