# Generated by Django 4.1.5 on 2023-03-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0031_commentmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.event'),
        ),
    ]
