# Generated by Django 4.1.5 on 2023-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0032_alter_commentmodel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='like',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='unlike',
            field=models.IntegerField(),
        ),
    ]
