# Generated by Django 4.1.5 on 2023-03-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0033_alter_likemodel_like_alter_likemodel_unlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
