# Generated by Django 4.1.5 on 2023-03-27 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0034_alter_likemodel_unlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='unlike',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
