# Generated by Django 4.1.5 on 2023-03-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0035_remove_likemodel_like_remove_likemodel_unlike_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='likes',
            new_name='name',
        ),
    ]
