# Generated by Django 4.1.5 on 2023-03-27 02:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0036_rename_likes_likemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='name',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
    ]
