# Generated by Django 4.1.5 on 2023-03-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0037_alter_likemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
