# Generated by Django 4.1.5 on 2023-03-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0038_remove_likemodel_name_likemodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='likes',
            field=models.BooleanField(default=True),
        ),
    ]
