# Generated by Django 4.1.5 on 2023-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0039_alter_likemodel_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likeModel',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.BooleanField(default=True),
        ),
    ]
