# Generated by Django 4.1.5 on 2023-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0040_delete_likemodel_commentmodel_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=True)),
            ],
        ),
    ]
