# Generated by Django 4.1.5 on 2023-03-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0041_likemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='likes',
            field=models.BooleanField(default=True, primary_key=True, serialize=False),
        ),
    ]
