# Generated by Django 4.1.5 on 2023-03-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0042_remove_likemodel_id_alter_likemodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='likes',
            field=models.BooleanField(default=True),
        ),
    ]
