# Generated by Django 4.1.5 on 2023-03-30 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0044_likemodel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.event'),
        ),
    ]
