# Generated by Django 4.1.5 on 2023-03-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0046_alter_likemodel_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
