# Generated by Django 4.1.5 on 2023-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0047_delete_likemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='cal.ipmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='cal.ipmodel'),
        ),
    ]
