# Generated by Django 4.1.5 on 2023-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0048_ipmodel_remove_commentmodel_likes_commentmodel_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('likes', models.BooleanField(default=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
