# Generated by Django 4.1.5 on 2023-03-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0049_likemodel_remove_commentmodel_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
