# Generated by Django 4.1.5 on 2023-03-30 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0051_commentmodel_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post_like',
        ),
        migrations.AddField(
            model_name='event',
            name='post_like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
