# Generated by Django 4.1.5 on 2023-03-30 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0052_remove_commentmodel_post_like_event_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
