# Generated by Django 4.1.5 on 2023-04-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0054_commentmodel_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post_like',
        ),
    ]
