# Generated by Django 4.1.5 on 2023-04-02 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0055_remove_commentmodel_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.event'),
        ),
    ]
