# Generated by Django 4.1.5 on 2023-04-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0058_commentmodel_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
