# Generated by Django 4.1.5 on 2023-04-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0059_alter_commentmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
